// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/dmitriidobr/GolandProjects/auth/internal/auth/service/auth.go

// Package mock_service is a generated GoMock package.
package mock

import (
	types "auth/internal/auth/types"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserAction is a mock of UserAction interface.
type MockUserAction struct {
	ctrl     *gomock.Controller
	recorder *MockUserActionMockRecorder
}

// MockUserActionMockRecorder is the mock recorder for MockUserAction.
type MockUserActionMockRecorder struct {
	mock *MockUserAction
}

// NewMockUserAction creates a new mock instance.
func NewMockUserAction(ctrl *gomock.Controller) *MockUserAction {
	mock := &MockUserAction{ctrl: ctrl}
	mock.recorder = &MockUserActionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAction) EXPECT() *MockUserActionMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserAction) CreateUser(ctx context.Context, user, password string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user, password)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserActionMockRecorder) CreateUser(ctx, user, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserAction)(nil).CreateUser), ctx, user, password)
}

// GetUser mocks base method.
func (m *MockUserAction) GetUser(ctx context.Context, username string) (*types.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, username)
	ret0, _ := ret[0].(*types.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserActionMockRecorder) GetUser(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserAction)(nil).GetUser), ctx, username)
}

// MockBroker is a mock of Broker interface.
type MockBroker struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerMockRecorder
}

// MockBrokerMockRecorder is the mock recorder for MockBroker.
type MockBrokerMockRecorder struct {
	mock *MockBroker
}

// NewMockBroker creates a new mock instance.
func NewMockBroker(ctrl *gomock.Controller) *MockBroker {
	mock := &MockBroker{ctrl: ctrl}
	mock.recorder = &MockBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroker) EXPECT() *MockBrokerMockRecorder {
	return m.recorder
}

// Notify mocks base method.
func (m *MockBroker) Notify(ctx context.Context, message types.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Notify", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Notify indicates an expected call of Notify.
func (mr *MockBrokerMockRecorder) Notify(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Notify", reflect.TypeOf((*MockBroker)(nil).Notify), ctx, message)
}

// MockCreatePassword is a mock of CreatePassword interface.
type MockCreatePassword struct {
	ctrl     *gomock.Controller
	recorder *MockCreatePasswordMockRecorder
}

// MockCreatePasswordMockRecorder is the mock recorder for MockCreatePassword.
type MockCreatePasswordMockRecorder struct {
	mock *MockCreatePassword
}

// NewMockCreatePassword creates a new mock instance.
func NewMockCreatePassword(ctrl *gomock.Controller) *MockCreatePassword {
	mock := &MockCreatePassword{ctrl: ctrl}
	mock.recorder = &MockCreatePasswordMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreatePassword) EXPECT() *MockCreatePasswordMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockCreatePassword) Generate(password string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", password)
	ret0, _ := ret[0].(string)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockCreatePasswordMockRecorder) Generate(password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockCreatePassword)(nil).Generate), password)
}
