// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/dmitriidobr/GolandProjects/auth/internal/auth/handler/handler.go

// Package mock_handler is a generated GoMock package.
package mock

import (
	types "auth/internal/auth/types"
	context "context"
	reflect "reflect"
	time "time"

	jwt "github.com/golang-jwt/jwt/v4"
	gomock "github.com/golang/mock/gomock"
)

// MockserviceAction is a mock of serviceAction interface.
type MockserviceAction struct {
	ctrl     *gomock.Controller
	recorder *MockserviceActionMockRecorder
}

// MockserviceActionMockRecorder is the mock recorder for MockserviceAction.
type MockserviceActionMockRecorder struct {
	mock *MockserviceAction
}

// NewMockserviceAction creates a new mock instance.
func NewMockserviceAction(ctrl *gomock.Controller) *MockserviceAction {
	mock := &MockserviceAction{ctrl: ctrl}
	mock.recorder = &MockserviceActionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockserviceAction) EXPECT() *MockserviceActionMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockserviceAction) Login(ctx context.Context, creds types.Login, header, body string) (time.Time, *jwt.Token, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, creds, header, body)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(*jwt.Token)
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Login indicates an expected call of Login.
func (mr *MockserviceActionMockRecorder) Login(ctx, creds, header, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockserviceAction)(nil).Login), ctx, creds, header, body)
}

// Refresh mocks base method.
func (m *MockserviceAction) Refresh(token string) (time.Time, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", token)
	ret0, _ := ret[0].(time.Time)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Refresh indicates an expected call of Refresh.
func (mr *MockserviceActionMockRecorder) Refresh(token interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockserviceAction)(nil).Refresh), token)
}

// Register mocks base method.
func (m *MockserviceAction) Register(ctx context.Context, user types.User, header, body string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, user, header, body)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockserviceActionMockRecorder) Register(ctx, user, header, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockserviceAction)(nil).Register), ctx, user, header, body)
}
