port: "localhost:9090"

db:
  host: "localhost"
  password: "qwerty"
  port: "5436"
  username: "postgres"
  dbname: "postgres"
  sslmode: "disable"
kafka:
  address: "localhost:29092"
  topic: "topicauth"
auth:
  salt: "nwueewui3212wlwo"
  jwtKey: "my_secret_key"
